### ISSUE TITLE
how to convert on osx ?

### ISSUE THREAD

**Issue by jt3k** [MrYadro/TDeskDroid#3]
i install python3 via  brew
![](https://i.imgur.com/4UpWAiD.png)

**Comment by MrYadro** [comment]
Can you read? https://github.com/MrYadro/TDeskDroid/blob/master/README.md

**Comment by jt3k** [comment]
@MrYadro yes..  i install `python3` and `pillow`.   After this  i  run  `pip install -r requirements.txt ` in project dir  

also i  restart my terminal

**Comment by MrYadro** [comment]
So what's the problem then?

**Comment by jt3k** [comment]
this is illustrated in the picture in [the first post](https://github.com/MrYadro/TDeskDroid/issues/3#issue-209134178)

**Comment by MrYadro** [comment]
Then you didn't install pillow.

**Comment by jt3k** [comment]
after i run the command  i  look  the error

**Comment by jt3k** [comment]
i install  it ![](https://i.imgur.com/py2x0dA.png)

**Comment by jt3k** [comment]
aghr ... i missed  the errors   about  link...

**Comment by MrYadro** [comment]
PYTHON **3** not 2.7

**Comment by MrYadro** [comment]
I think you need to run `brew install python3` and `brew install pip3` if you cant / wont use official python 3 installer.

**Comment by jt3k** [comment]
I noticed that pillow is installed for Python 2.7  but.. we using python3
![](https://i.imgur.com/s6QZGFb.png)
hm..

how to install pillow for  python3 ?

**Comment by jt3k** [comment]
ok i try install `pip3 `

**Comment by jt3k** [comment]
does not work. I went to Google.
![](https://i.imgur.com/D60uEKs.png)

**Comment by MrYadro** [comment]
Can you run `pip3 install -r requirements.txt` you don't need to install pillow via brew.

**Comment by jt3k** [comment]
ok !
![](https://i.imgur.com/BPcvBn6.png)

I have no idea how to fix it

**Comment by MrYadro** [comment]
How did you install python at first place?

**Comment by jt3k** [comment]
my operating-system  includes python 2.7 after install

to install Python 3 I ran `brew install python3` (now i have  python3-3.6.0)

**Comment by MrYadro** [comment]
Check this guide - https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-macos
Maybe you need xcode to run python. Brew should install pip3 all by itself.

**Comment by jt3k** [comment]
still not works....

![](https://i.imgur.com/UkOHYs1.png)

**Comment by MrYadro** [comment]
Can you run `pip3 install pillow`?
Weird system you have, never had such problems on it.

**Comment by jt3k** [comment]
! WORKED!!!   THANXX!!

![](https://i.imgur.com/N2cfP8u.png)

**Comment by jt3k** [comment]
THANX FOR SUPPORT!!
